version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-controle-financas
    environment:
      POSTGRES_DB: controle_financas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: controle-financas
    container_name: controle-financas-backend
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/controle_financas
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
    ports:
      - "9000:9000"

volumes:
  pgdata: