version: "3.8"

services:
  postgres-pessoal:
    image: postgres:15
    container_name: postgres-pessoal
    restart: unless-stopped
    environment:
      POSTGRES_DB: controle_financas
      POSTGRES_USER: financas
      POSTGRES_PASSWORD: financas
    ports:
      - "5433:5432"
    volumes:
      - postgres_pessoal_data:/var/lib/postgresql/data

volumes:
  postgres_pessoal_data:
